@host = 127.0.0.1
@port = 3500

###

# check system status
GET http://{{host}}:{{port}}/v1.0/metadata

###

# Check agent is alive

PUT http://{{host}}:{{port}}/v1.0/actors/greet/1/method/x
content-type: application/json

"JUGSAW"

###

# Check agent is alive

# @name greet
POST http://{{host}}:8081/actors/greet/jinguo/method/

"Jinguo"

#####

@greet_res_ref = {{greet.response.body.*}}

POST http://{{host}}:8081/actors/greet/jinguo/method/fetch

"{{greet_res_ref}}"

###

# @name count
POST http://{{host}}:8081/actors/Counter/juntian/method/

5

#####

@count_res_ref = {{count.response.body.*}}

POST http://{{host}}:8081/actors/Counter/juntian/method/fetch

"{{count_res_ref}}"