[deps]
Jugsaw = "506f6749-58fa-473a-ada6-eb0172fb6950"
TensorInference = "c2297e78-99bd-40ad-871d-f50e56b81012"

[compat]
julia = "1"

[jugsaw]
name = "inference"
uuid = "b3281a61-e607-4d50-a4de-9196c1fa9462"
authors = "GiggleLiu <cacate0129@gmail.com> and contributors"
version = "1.0.0-DEV"
