apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jobmanager.fullname" . }}
  labels:
    {{- include "jobmanager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jobmanager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jobmanager.selectorLabels" . | nindent 8 }}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "{{ .Chart.Name }}"
        dapr.io/app-port: "{{ .Values.service.port }}"
        dapr.io/log-level: "debug"
    spec:
      serviceAccountName: dapr-service-account
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.registry }}/{{ .Values.image.project }}/{{ .Values.image.name | default .Chart.Name}}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python"]
          args: ["-m", "uvicorn", "api.job_manager:app", "--host", "0.0.0.0", "--port", "{{ .Values.service.port }}"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
