@host = 127.0.0.1
@port = 3500

###

# Check agent is alive

# @name proj
GET http://{{host}}:{{port}}/api/v1/proj

#####

# @name greet
POST http://{{host}}:{{port}}/v1.0/publish/jobs/starting
Content-Type: application/json
Accept: application/json

{
    "id": "000",
    "created_at": 1683877867.7322347,
    "created_by": "VSCode",

    "app": "helloworld",
    "ver": "latest",
    "func": "greet",
    "data": "{\"name\": \"Jugsaw\"}"
}

#####

@greet_res_ref = {{greet.response.body.*}}

POST http://{{host}}:8081/actors/greet/jinguo/method/fetch

{{greet_res_ref}}

###

# @name count
POST http://{{host}}:8081/actors/Counter/juntian/method/
Content-Type: application/json
Accept: application/json

{
    "__type__" : "JugsawIR.Call{Core.DataType, Core.Tuple{Core.Int64}, Core.NamedTuple{(), Core.Tuple{}}}",
    "fname" : "Main.Counter",
    "args" : {"data":[2]},
    "kwargs" : {}
}

#####

@count_res_ref = {{count.response.body.*}}

POST http://{{host}}:8081/actors/Counter/juntian/method/fetch

{{count_res_ref}}