@host = 127.0.0.1
@port = 8081

###

# Check agent is alive

# @name greet
POST http://{{host}}:8081/actors/greet/jinguo/method/
Content-Type: application/json
Accept: application/json

{
    "__type__" : "Jugsaw.JugsawFunctionCall{Main.#greet, Core.Tuple{Core.String}, Core.NamedTuple{(), Core.Tuple{}}}",
    "fname" : "#greet",
    "args" : {"data":["Jugsaw"]},
    "kwargs" : {}
}

#####

@greet_res_ref = {{greet.response.body.*}}

POST http://{{host}}:8081/actors/greet/jinguo/method/fetch

{{greet_res_ref}}

###

# @name count
POST http://{{host}}:8081/actors/Counter/juntian/method/
Content-Type: application/json
Accept: application/json

{
    "__type__" : "Jugsaw.JugsawFunctionCall{Core.DataType, Core.Tuple{Core.Int64}, Core.NamedTuple{(), Core.Tuple{}}}",
    "fname" : "Main.Counter",
    "args" : {"data":[2]},
    "kwargs" : {}
}

#####

@count_res_ref = {{count.response.body.*}}

POST http://{{host}}:8081/actors/Counter/juntian/method/fetch

{{count_res_ref}}