expr: object
        | string
        | number
        | true
        | false
        | null

object : "[" [expr ("," expr)*] "]"
call : symbol [expr (expr)*] [kwarg (kwarg)*]
kwarg: symbol "=" expr
string : ESCAPED_STRING
symbol : /[a-zA-Z_][a-zA-Z_0-9]*/
number : SIGNED_NUMBER
true : "true"
false : "false"
null : "null"
COMMENT: "#" /[^\n]/*

%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.WS
%ignore WS
%ignore COMMENT