apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: jugsaw-job-result-store
spec:
  type: pubsub.redis
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""
    - name: keyPrefix
      value: name